Repository add-ons/plugin.video.redbull.tv, pull requests merged in 2021-01, with the labels that each got.

#28 Add Python 3.9 support
  .github/workflows/addon-check.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .github/workflows/status.yml
  tox.ini
Labels: testing

#29 Fix Makefile multizip
  Makefile
Labels: testing

#31 Prepare for v3.2.2 release
  README.md
  addon.xml
Labels: release

#35 Small fixes
  resources/lib/redbull.py
Labels: bug

#36 Make use of git archive
  Makefile
  addon.xml
Labels: testing

#34 Allow to install and run Kodi Logfile Uploader from the settings
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/settings.xml
Labels: enhancement
